### ISSUE TITLE
Differences in results of `extend_synonyms`

### ISSUE THREAD

**Issue by ma-ilsi** [SinaLab/sinatools#3]
Firstly, thank you for the amazing work. The tools and their demos are very helpful.

When calling `extend_synonyms("عسكري", 3)` on a local machine and the demo, I receive very different results:

Local machine:
<img width="615" alt="Screenshot 2024-11-03 at 1 27 57 PM" src="https://github.com/user-attachments/assets/fcff0156-87c5-4519-b283-4220cf39627f">

Online demo:
<img width="1163" alt="Screenshot 2024-11-03 at 1 29 53 PM" src="https://github.com/user-attachments/assets/f46353be-9549-478b-9e1c-34551a0b635b">

This is the case for pretty much any word. Why are the local results different from the online tool?

**Comment by nabila39** [comment]
Thank you for your note. We have updated the synonyms dictionary. Please download it again using the download command as described in the [documentation](https://sina.birzeit.edu/sinatools/documentation/installation.html#installation). Additionally, please note that the synonyms demo includes a checkbox labeled "Use ALMA." If this checkbox is selected, the results will differ from those of SinaTools, as this is an extension for enhancing the [demo](https://sina.birzeit.edu/synonyms/).
